### ISSUE TITLE
it stopped working

### ISSUE THREAD

**Issue by joukeHijlkema** [milouse/flycheck-grammalecte#23]
Hi,
First of all thank you very much for your work. I've been using this in emacs for some time now, and it is great.
However, since my last emacs update, Grammalecte stopped working, and I need some tips to find out why.

My emacs version (git pull and compiled with configure --with-xwidgets)
`GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34,  cairo version 1.16.0) of 2022-12-01`

Before, when flycheck was active in latex mode for instance, I had the grammalect corrections. Now there is nothing, not even an error message. I tried 
`(setq flycheck-grammalecte--debug-mode t)`
But that does not seem to do much. Do you have any idea why this happened or how to debug this issue ?

Thanks a lot,

Jouke

**Comment by milouse** [comment]
Hi,

I don’t know this version, but it looks like something change either in this new Emacs version, or in your configuration, or in the way Emacs understand your configuration.

Just to be sure it is not related to your configuration, but to this new Emacs version, you can try to check if the little demo present in this repository works or not with your Emacs version. You just have to clone this repository, then run `make demo` in your console. It should launch your Emacs version, but with a stripped down profile. Just open the provided "exemple.org" file and check if flycheck-grammalecte works as expected or not. 

If it works, the problem is in your configuration. It is totally possible that something else breaks in your config before flycheck-grammalecte loading, and that’s why it is never loaded. Also check how you are loading flycheck-grammalecte (require, load file, use-package, straight…) and if that way have change or not with the new Emacs version.

Finally if it does not work in the demo, it means there is some kind of incompatibility between this package and the new version. I may try to compile it myself later to check if I found something or not.

**Comment by joukeHijlkema** [comment]
Salut Étienne,

The demo does not work, and I get the following warnings:

⛔ Warning (comp): flycheck-grammalecte.el:141:2: Warning:
custom-declare-variable `flycheck-grammalecte-filters' docstring has wrong
usage of unescaped single quotes (use \= or different quoting)
⛔ Warning (comp): flycheck-grammalecte.el:226:2: Warning:
custom-declare-variable `flycheck-grammalecte-predicate' docstring has
wrong usage of unescaped single quotes (use \= or different quoting)
⛔ Warning (comp): org-loaddefs.el.gz:846:61: Warning: Unused lexical
variable `org-element-use-cache'

Not sure this will keep it from working though

Jouke

**Comment by joukeHijlkema** [comment]
... Am I correct that ./flycheck_grammalecte.py example.org should check
the file example.org from the CL ? It complains about missing module
grammalecte. I looked and I could only find pygrammalecte that does not
provide the same methods ... What python package are you calling ?

**Comment by milouse** [comment]
Looks like a bug in the `grammalecte-download-grammalecte` function. As a temporary work around, you can try to download grammalecte manually. Download it here https://grammalecte.net/zip/Grammalecte-fr-v2.1.1.zip and unzip it. You will got a bunch of folders and files. You just need to take the folder called `grammalecte` and move it inside the flycheck-grammalecte install folder (even if it comes from melpa). Then restart Emacs and normally it should work again. If not, I’ll need to really try on my side, I’ll try to take some time asap.

**Comment by joukeHijlkema** [comment]
:-) Funny.

I just wanted to tell you the same thing. I think Grammalecte moved its
repository, since https://grammalecte.net/zip/ no longer exists (or refuses
access). I think the error is on their side. I downloaded the zip file and
now things are working again.

Merci et bonne journée,
Jouke

**Comment by milouse** [comment]
With a second look I found the origin of the problem. Old URL were `https://grammalecte.net/grammalecte/zip/…` while new ones are `https://grammalecte.net/zip/…` (`grammalecte` subfolder has been removed). I’ve just pushed a quick fix and a new release for that. Thank you very much for the notification.
